--- #YAML:1.0
name:               Net-Amazon-S3-Client-GPG
version:            0.33
abstract:           Use GPG with Amazon S3 - Simple Storage Service
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    GnuPG::Interface:  0
    Net::Amazon::S3:   0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
